### ISSUE TITLE
Reconcile data from HPD and HCR

### ISSUE THREAD

**Issue by Redoudou** [leaseOTB/test-data-scraping#3]
There is 3 files enclosed. Those are selection of the buildings located in the neighborhoods for the NYCx challenge. (zip code 10031, 10032, 10033, 10034, 10040)
I would need your help to import those 3 files in a data base of your choice. Then make some left and right join to identify what data are not in what space. I discovered that the BIN field in HPD extract sometime match the Building Registration Number of HCR.  We have then a Key to reconcile both data source.  HPD and HCR seems to have the same Granularity at building level.
Here the query I would need your help running between HPD and HCR NYCx Data sources :
[HCR-NYCx.txt](https://github.com/leaseOTB/test-data-scraping/files/4867242/HCR-NYCx.txt)
[HPD-NYCx.txt](https://github.com/leaseOTB/test-data-scraping/files/4867243/HPD-NYCx.txt)
[HUD-NYCx.txt](https://github.com/leaseOTB/test-data-scraping/files/4867244/HUD-NYCx.txt)

`[BIN].HPD-NYCX Leftjoin [Building Registration Number].HCR-NYCX` >> I want to know how many records exist only in HPD data source
Name de file HPD-LJ-HCR.csv
`[BIN].HPD-NYCX Rightjoin [Building Registration Number].HCR-NYCX` >> I want to know how many records exist only in HCR data source
 Name the file HPD-RJ-HCR.csv
`[BIN].HPD-NYCX Innerjoin [Building Registration Number].HCR-NYCX`  >> I want to know how many records exist in both HCR and HPD
Name the file HPD.Inner.HCR.csv
When building those query try to keep in mind that the code must be re-usable in the future. We will use those query again.

**Comment by apnavp** [comment]
Done. Can be found [here](https://drive.google.com/drive/u/1/folders/1PQaddh9ukmD3_5phrSt8kPabtSPgC525l)
